2021-09-14 18:52:00.9279 - ERROR - 80000002-0004-ff00-b63f-84710c7967bb - (POST) https://localhost/api/v1/Auth/CredentialsLogin (ver: ) - ::1
     Message: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
     Exception: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
     StackTrace:    at ParImparApi.Services.AuthService.ValidateLocalCredentialsLogin(CredentialsLoginRequestDTO credentialsLoginRequest) in C:\Users\User\Desktop\Gaston\UTN\Proyecto\GitHub\PF2021G12\Com_parImpar_API\ParImparApi\Services\AuthService.cs:line 304
   at ParImparApi.Services.AuthService.ValidateLocalCredentialsLogin(CredentialsLoginRequestDTO credentialsLoginRequest) in C:\Users\User\Desktop\Gaston\UTN\Proyecto\GitHub\PF2021G12\Com_parImpar_API\ParImparApi\Services\AuthService.cs:line 312
   at ParImparApi.Services.AuthService.CredentialsLogin(CredentialsLoginRequestDTO credentialsLoginRequest) in C:\Users\User\Desktop\Gaston\UTN\Proyecto\GitHub\PF2021G12\Com_parImpar_API\ParImparApi\Services\AuthService.cs:line 36
   at ParImparApi.Controllers.AuthController.CredentialsLogin(CredentialsLoginRequestDTO credentialsLoginRequest) in C:\Users\User\Desktop\Gaston\UTN\Proyecto\GitHub\PF2021G12\Com_parImpar_API\ParImparApi\Controllers\AuthController.cs:line 46
     Headers: Authorization="", 
     Body: {"User":"test@gmail.com","Password":"test123!","KeepLoggedIn":true}

2021-09-14 18:52:00.9279 - ERROR - 80000002-0000-ff00-b63f-84710c7967bb - (POST) https://localhost/api/v1/Auth/CredentialsLogin (ver: ) - ::1
     Message: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
     Exception: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
     StackTrace:    at ParImparApi.Services.AuthService.ValidateLocalCredentialsLogin(CredentialsLoginRequestDTO credentialsLoginRequest) in C:\Users\User\Desktop\Gaston\UTN\Proyecto\GitHub\PF2021G12\Com_parImpar_API\ParImparApi\Services\AuthService.cs:line 304
   at ParImparApi.Services.AuthService.ValidateLocalCredentialsLogin(CredentialsLoginRequestDTO credentialsLoginRequest) in C:\Users\User\Desktop\Gaston\UTN\Proyecto\GitHub\PF2021G12\Com_parImpar_API\ParImparApi\Services\AuthService.cs:line 312
   at ParImparApi.Services.AuthService.CredentialsLogin(CredentialsLoginRequestDTO credentialsLoginRequest) in C:\Users\User\Desktop\Gaston\UTN\Proyecto\GitHub\PF2021G12\Com_parImpar_API\ParImparApi\Services\AuthService.cs:line 36
   at ParImparApi.Controllers.AuthController.CredentialsLogin(CredentialsLoginRequestDTO credentialsLoginRequest) in C:\Users\User\Desktop\Gaston\UTN\Proyecto\GitHub\PF2021G12\Com_parImpar_API\ParImparApi\Controllers\AuthController.cs:line 46
     Headers: Authorization="", 
     Body: {"User":"test@gmail.com","Password":"test123!","KeepLoggedIn":true}

2021-09-14 18:52:21.9647 - ERROR - 80000006-0003-ff00-b63f-84710c7967bb - (POST) https://localhost/api/v1/Auth/CredentialsLogin (ver: ) - ::1
     Message: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
     Exception: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
     StackTrace:    at ParImparApi.Services.AuthService.ValidateLocalCredentialsLogin(CredentialsLoginRequestDTO credentialsLoginRequest) in C:\Users\User\Desktop\Gaston\UTN\Proyecto\GitHub\PF2021G12\Com_parImpar_API\ParImparApi\Services\AuthService.cs:line 304
   at ParImparApi.Services.AuthService.ValidateLocalCredentialsLogin(CredentialsLoginRequestDTO credentialsLoginRequest) in C:\Users\User\Desktop\Gaston\UTN\Proyecto\GitHub\PF2021G12\Com_parImpar_API\ParImparApi\Services\AuthService.cs:line 312
   at ParImparApi.Services.AuthService.CredentialsLogin(CredentialsLoginRequestDTO credentialsLoginRequest) in C:\Users\User\Desktop\Gaston\UTN\Proyecto\GitHub\PF2021G12\Com_parImpar_API\ParImparApi\Services\AuthService.cs:line 36
   at ParImparApi.Controllers.AuthController.CredentialsLogin(CredentialsLoginRequestDTO credentialsLoginRequest) in C:\Users\User\Desktop\Gaston\UTN\Proyecto\GitHub\PF2021G12\Com_parImpar_API\ParImparApi\Controllers\AuthController.cs:line 46
     Headers: Authorization="", 
     Body: {"User":"test@gmail.com","Password":"test123!","KeepLoggedIn":true}

2021-09-14 20:46:38.2671 - INFO - 80000010-0004-ff00-b63f-84710c7967bb - (GET) https://localhost/api/v1/Events/Date?d=2021-08-10 (ver: ) - ::1
     Message: Start date is required
     Headers: Authorization="", 

